from pathlib import Path

import streamlit as st

from auth import initialize_session, logout, require_any_access
from utils import (
    apply_custom_style,
    build_threat_indicators,
    compute_compliance,
    load_json,
    render_divider,
    render_hero,
    render_kpi_card,
    render_section_header,
    render_sidebar,
    render_status_strip,
    render_tactic_coverage_chart,
    render_threat_indicator_cards,
    render_threat_ticker,
)

st.set_page_config(page_title="Threat Intelligence", page_icon="🧬", layout="wide")
apply_custom_style()
initialize_session()
require_any_access(["admin", "it", "compliance"])

BASE_DIR = Path(__file__).resolve().parent.parent
controls = load_json(BASE_DIR / "control_bank.json")
system = load_json(BASE_DIR / "system_data.json")
summary = compute_compliance(controls, system)
user = st.session_state.user

render_sidebar(user, summary, system)
render_hero(
    "Threat Intelligence & Exposure Mapping",
    "Failed and insufficient-evidence controls, translated into SOC-style threat indicators and mapped to illustrative MITRE ATT&CK tactics.",
    "Live Threat Correlation",
)

indicators = build_threat_indicators(summary["results"], system)
high_count = len([i for i in indicators if i["severity"] == "High"])
medium_count = len([i for i in indicators if i["severity"] == "Medium"])
low_count = len([i for i in indicators if i["severity"] == "Low"])
tactics_touched = len(set(i["tactic"] for i in indicators))

c1, c2, c3, c4 = st.columns(4)
with c1:
    render_kpi_card("Active Indicators", str(len(indicators)), "Findings + live telemetry mapped to ATT&CK", "danger" if indicators else "success", "🧬")
with c2:
    render_kpi_card("Critical Exposure", str(high_count), "High-severity indicators needing priority response", "danger" if high_count else "success", "🔴")
with c3:
    render_kpi_card("ATT&CK Tactics Touched", str(tactics_touched), "Distinct adversary tactics represented", "warning" if tactics_touched else "success", "🗺️")
with c4:
    render_kpi_card("Compliance Score", f"{summary['percent']:.1f}%", "Overall control effectiveness feeding this view", "success" if summary["percent"] >= 85 else "warning" if summary["percent"] >= 60 else "danger", "🎯")

render_divider()
render_section_header("Live Indicator Feed", "Streaming summary of every active indicator currently correlated by the platform.", "📡")
render_threat_ticker(indicators)

render_status_strip([
    ("Telemetry ingestion: nominal", "ok"),
    ("Suspicious IP correlation: " + ("active hit" if system.get("suspicious_ip_detected") else "clear"), "crit" if system.get("suspicious_ip_detected") else "ok"),
    ("After-hours access correlation: " + ("active hit" if system.get("after_hours_access") else "clear"), "warn" if system.get("after_hours_access") else "ok"),
])

render_divider()
left, right = st.columns([1, 1])
with left:
    render_section_header("Severity Distribution", "Active indicators grouped by severity tier.", "📊")
    sc1, sc2, sc3 = st.columns(3)
    with sc1:
        render_kpi_card("High", str(high_count), "Immediate response", "danger", "🟥")
    with sc2:
        render_kpi_card("Medium", str(medium_count), "Scheduled remediation", "warning", "🟨")
    with sc3:
        render_kpi_card("Low", str(low_count), "Monitor", "success", "🟩")
with right:
    render_tactic_coverage_chart(indicators)

render_divider()
render_section_header("Threat Indicator Details", "Each indicator includes its source control, illustrative ATT&CK technique, and recommended response.", "🛰️")
render_threat_indicator_cards(indicators, limit=10)

render_divider()
render_section_header("About This View", "How indicators here are generated.", "ℹ️")
st.markdown(
    """
<div class="hc-card">
    <div class="hc-subtitle">
        Indicators are generated by correlating failed or insufficient-evidence controls from the compliance engine,
        plus live signals from system telemetry (suspicious IPs, after-hours access, excessive record access, and role
        mismatches). Each indicator is tagged with an illustrative MITRE ATT&amp;CK tactic and technique for educational
        purposes, so security and compliance teams can discuss exposure using a shared, industry-standard vocabulary.
        This is a simplified teaching mapping and is not a substitute for a full ATT&amp;CK Navigator assessment.
    </div>
</div>
""",
    unsafe_allow_html=True,
)

render_divider()
if st.button("Logout"):
    logout()
    st.rerun()
